os:
  edit: 'teapot git edit {{filename}}'
  editAtLine: 'teapot git edit-line {{filename}} {{line}}'
  editAtLineAndWait: 'teapot git edit-line {{filename}} {{line}}'
  editInTerminal: false
  openDirInEditor: 'teapot git open-dir {{dir}}'

keybinding:
  universal:
    pushFiles: 'p'
    pullFiles: 'P'
  files:
    commitChanges: 'C'
    commitChangesWithEditor: 'c'
  
