# Starship configurations

# editor completion "not working in helix"
"$schema" = "https://starship.rs/config-schema.json"

# Don't print a new line at the start of the prompt
add_newline = false

[character]
format = "$symbol [ ](fg:#a6e3a1)"
success_symbol = "[](bold fg:#a6e3a1)" 
error_symbol = "[](bold fg:#f38ba8)"
vicmd_symbol = "[  ](bold fg:#a6e3a1)"

# Battery Module
[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[[battery.display]] 
threshold = 10
style = "bold #f38ba8"

[[battery.display]]
threshold = 20
style = "bold #fab387"

# Directory Module
[directory]
style = "bold #89b4fa"
truncation_length = 3
truncation_symbol = "_/"
read_only = "  "
read_only_style = "#45475a"

# Git Module
[git_branch]
style = "bold #fab387"

[git_commit]
style = "bold #89dceb"

[git_status]
style = "bold #cba6f7"

[git_metrics]
disabled = false
added_style = "bold #a6e3a1"
deleted_style = "bold #f38ba8"

[git_state]
style = "bold #cba6f7"

[package]
format = "via [ $version](208 bold) "
